/*Integrantes 
    Andrey Pérez Granados
    David Fallas Morales
 */
package Admin;

import Estructuras.Estructuras;
import javax.swing.JOptionPane;

public class AgregarPremios_Admin extends javax.swing.JFrame {

    private Usuarios.Dato usuarioActivo;
    private Estructuras estructurasDatosObject;
    private Premios.Dato datoPremios;
    private Posición.ListaDobleCircular accionPremios;
    /**
     * Creates new form AgregarPremios_Admin
     */
    public AgregarPremios_Admin() {
        initComponents();
    }

    public AgregarPremios_Admin(Estructuras objeto, Usuarios.Dato usuarioActivo) {
        initComponents();
        setLocationRelativeTo(null);
        this.estructurasDatosObject = objeto;
        this.usuarioActivo = usuarioActivo;
        this.datoPremios = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uiAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        uiPuntajePremio = new javax.swing.JTextField();
        labelDescPremio = new javax.swing.JLabel();
        labelDescPremio1 = new javax.swing.JLabel();
        uiPremio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uiGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        uiAtras.setBackground(new java.awt.Color(0, 0, 0));
        uiAtras.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiAtras.setForeground(new java.awt.Color(255, 255, 255));
        uiAtras.setText("Atrás");
        uiAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAtrasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Agregar Premios");

        uiPuntajePremio.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        labelDescPremio.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        labelDescPremio.setForeground(new java.awt.Color(255, 255, 255));
        labelDescPremio.setText("Digite el nombre del premio:");

        labelDescPremio1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        labelDescPremio1.setForeground(new java.awt.Color(255, 255, 255));
        labelDescPremio1.setText("Digite el valor del premio:");

        uiPremio.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        uiPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiPremioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Todo listo?");

        uiGuardar.setBackground(new java.awt.Color(0, 0, 0));
        uiGuardar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiGuardar.setForeground(new java.awt.Color(255, 255, 255));
        uiGuardar.setText("Guardar Cambios");
        uiGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDescPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDescPremio1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uiPuntajePremio, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uiAtras)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(uiGuardar)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(uiAtras))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescPremio)
                    .addComponent(uiPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDescPremio1)
                    .addComponent(uiPuntajePremio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uiGuardar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAtrasActionPerformed

        MenúAdmin atras = new MenúAdmin(estructurasDatosObject, usuarioActivo);
        atras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uiAtrasActionPerformed

    private void uiGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiGuardarActionPerformed
        String Premio = uiPremio.getText();
        int valorPremio = Integer.parseInt(uiPuntajePremio.getText());
        if (uiPremio.getText().isEmpty()&& (uiPuntajePremio.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Error - Favor digite un nombre de premio y su puntaje respectivo!");
        }else{
            datoPremios.setDescripcion(Premio);
            datoPremios.setIdPremio(valorPremio);
            //accionPremios.agregar(datoPremios);
        }
    }//GEN-LAST:event_uiGuardarActionPerformed

    private void uiPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiPremioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiPremioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPremios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPremios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPremios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPremios_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPremios_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescPremio;
    private javax.swing.JLabel labelDescPremio1;
    private javax.swing.JButton uiAtras;
    private javax.swing.JButton uiGuardar;
    private javax.swing.JTextField uiPremio;
    private javax.swing.JTextField uiPuntajePremio;
    // End of variables declaration//GEN-END:variables
}
