/*Integrantes 
    Andrey Pérez Granados
    David Fallas Morales
    Ericson Tames Quesada  

temas
    Base de datos: mysql
    SWING GUI
    Colecciones
    Excepciones
*/
package Admin;

import Estructuras.Estructuras;
import Inicio_Sesion.Inicio;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class AgregarMarcador_Admin extends javax.swing.JFrame {
    private Usuarios.Dato usuarioActivo;
    private Estructuras estructurasDatosObject;
    
    
    private LinkedList<Marcadores> PuntosUsuario;

    /**
     * Creates new form AgreagarMarcador
     */
    public AgregarMarcador_Admin() {
        initComponents();
    }

    public AgregarMarcador_Admin(Estructuras objeto, Usuarios.Dato usuarioActivo) {
        initComponents();
        this.usuarioActivo = usuarioActivo;
        this.estructurasDatosObject = objeto;
        setLocationRelativeTo(null);
        mostrarTablaMarcadores();
        mostrarTablaFinalizados();
    }
    
    
    private void ActualizarTabla(){
        estructurasDatosObject.getColaPartidos().desencolar(estructurasDatosObject);
    }

    private void mostrarTablaMarcadores() {
        DefaultTableModel estructura = (DefaultTableModel) uiTablaMarcadores.getModel();
        //Limpia Jtable
        estructura.setRowCount(0);
            
        estructura = estructurasDatosObject.getColaPartidos().ColaATabla(estructura, 0);
        uiTablaMarcadores.getModel();
    }
    
    private void mostrarTablaFinalizados() {
        DefaultTableModel estructura = (DefaultTableModel) uiTablaFinalizados.getModel();
        //Limpia Jtable
        estructura.setRowCount(0);
            
        estructura = estructurasDatosObject.getListaCS_partidosFinalizados().ListaATabla(estructura, 0);
        uiTablaFinalizados.getModel();
    }
    
    private void sumaPuntos(){
            
            estructurasDatosObject.getListaCS_partidosFinalizados().sumaPuntos(estructurasDatosObject);
                    
            estructurasDatosObject.getListaSimple_marcadoresUsuario().crearTablaPosiciones(estructurasDatosObject);
            JOptionPane.showMessageDialog(null, estructurasDatosObject);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAgregarPartidos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        uiAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        uiTablaFinalizados = new javax.swing.JTable();
        uiExtraerPartido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uiTablaMarcadores = new javax.swing.JTable();
        uiGuardar = new javax.swing.JButton();

        labelAgregarPartidos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelAgregarPartidos.setText("Partidos Registrados");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        uiAtras.setBackground(new java.awt.Color(0, 0, 0));
        uiAtras.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiAtras.setForeground(new java.awt.Color(255, 255, 255));
        uiAtras.setText("Atrás");
        uiAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAtrasActionPerformed(evt);
            }
        });

        uiTablaFinalizados.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        uiTablaFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Partido", "Equipo Local", "Equipo Visitante", "Marcador Local", "Marcador Visitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uiTablaFinalizados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        uiTablaFinalizados.setName(""); // NOI18N
        jScrollPane1.setViewportView(uiTablaFinalizados);

        uiExtraerPartido.setBackground(new java.awt.Color(0, 0, 0));
        uiExtraerPartido.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiExtraerPartido.setForeground(new java.awt.Color(255, 255, 255));
        uiExtraerPartido.setText("Extraer partido finalizado");
        uiExtraerPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiExtraerPartidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Partidos Finalizados");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Marcadores");

        uiTablaMarcadores.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        uiTablaMarcadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Partido", "Equipo Local", "Equipo Visitante", "Marcador Local", "Marcador Visitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        uiTablaMarcadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        uiTablaMarcadores.setName(""); // NOI18N
        jScrollPane2.setViewportView(uiTablaMarcadores);

        uiGuardar.setBackground(new java.awt.Color(0, 0, 0));
        uiGuardar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiGuardar.setForeground(new java.awt.Color(255, 255, 255));
        uiGuardar.setText("Guardar cambios");
        uiGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 256, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(uiGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiExtraerPartido)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(252, 252, 252))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(uiAtras)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(260, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(245, 245, 245)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uiAtras)
                .addGap(251, 251, 251)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiExtraerPartido)
                    .addComponent(uiGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel3)
                    .addContainerGap(596, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAtrasActionPerformed
        MenúAdmin atras = new MenúAdmin(estructurasDatosObject, usuarioActivo);
        atras.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_uiAtrasActionPerformed

    private void uiExtraerPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiExtraerPartidoActionPerformed
        ActualizarTabla(); // metodo para pasar de Cola de partidos a Lista circular simple
        mostrarTablaMarcadores();
        mostrarTablaFinalizados();
        sumaPuntos();
        JOptionPane.showMessageDialog(null, "¡Valores Actualizados exitosamente!");
    }//GEN-LAST:event_uiExtraerPartidoActionPerformed

    private void uiGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiGuardarActionPerformed
        guardarCambios();
    }//GEN-LAST:event_uiGuardarActionPerformed
    
    public void guardarCambios(){
        TableModel tabla = uiTablaMarcadores.getModel();
        int idPartido = Integer.parseInt(String.valueOf(tabla.getValueAt(0, 0)));
        int marcadorL = Integer.parseInt(String.valueOf(tabla.getValueAt(0, 3)));
        int marcadorV = Integer.parseInt(String.valueOf(tabla.getValueAt(0, 4)));
        estructurasDatosObject.getColaPartidos().guardarCambios(marcadorL, marcadorV);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMarcador_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMarcador_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMarcador_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMarcador_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMarcador_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgregarPartidos;
    private javax.swing.JButton uiAtras;
    private javax.swing.JButton uiExtraerPartido;
    private javax.swing.JButton uiGuardar;
    private javax.swing.JTable uiTablaFinalizados;
    private javax.swing.JTable uiTablaMarcadores;
    // End of variables declaration//GEN-END:variables

}
