package Admin;

import Inicio_Sesion.Inicio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import Posición.TablaPosiciones;
import Estructuras.Estructuras;
public class MenúAdmin extends javax.swing.JFrame {
    private Usuarios.Dato usuarioActivo;
    private Estructuras estructurasDatosObject;
    /**
     * Creates new form MenúAdmin
     */
    
    public MenúAdmin() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public MenúAdmin(Estructuras objeto, Usuarios.Dato usuarioActivo) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioActivo = usuarioActivo;
        this.estructurasDatosObject = objeto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        labelMenuAdmin = new javax.swing.JLabel();
        uiAgPartidos = new javax.swing.JButton();
        uiAgMarcadores = new javax.swing.JButton();
        uiVerRanking = new javax.swing.JButton();
        uiCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelMenuAdmin1 = new javax.swing.JLabel();
        labelMenuAdmin2 = new javax.swing.JLabel();
        uiUsuarioAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 102, 102));

        labelMenuAdmin.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        labelMenuAdmin.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuAdmin.setText("¡Bienvenido al Menu Administrador!");

        uiAgPartidos.setBackground(new java.awt.Color(0, 0, 0));
        uiAgPartidos.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiAgPartidos.setForeground(new java.awt.Color(255, 255, 255));
        uiAgPartidos.setText("Agregar Partidos");
        uiAgPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAgPartidosActionPerformed(evt);
            }
        });

        uiAgMarcadores.setBackground(new java.awt.Color(0, 0, 0));
        uiAgMarcadores.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiAgMarcadores.setForeground(new java.awt.Color(255, 255, 255));
        uiAgMarcadores.setText("Agregar Marcadores");
        uiAgMarcadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAgMarcadoresActionPerformed(evt);
            }
        });

        uiVerRanking.setBackground(new java.awt.Color(0, 0, 0));
        uiVerRanking.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiVerRanking.setForeground(new java.awt.Color(255, 255, 255));
        uiVerRanking.setText("Ver Ranking");
        uiVerRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiVerRankingActionPerformed(evt);
            }
        });

        uiCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        uiCerrarSesion.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        uiCerrarSesion.setText("Cerrar Sesion");
        uiCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Admin_Logo.png"))); // NOI18N

        labelMenuAdmin1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        labelMenuAdmin1.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuAdmin1.setText("ADMIN :");

        labelMenuAdmin2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        labelMenuAdmin2.setForeground(new java.awt.Color(255, 255, 255));
        labelMenuAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenuAdmin2.setText("¿Deseas salir?");

        uiUsuarioAdmin.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        uiUsuarioAdmin.setText("USER");

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMenuAdmin)
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(uiVerRanking, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uiAgMarcadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(uiAgPartidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(uiCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMenuAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelMenuAdmin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uiUsuarioAdmin)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelMenuAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(uiAgPartidos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uiAgMarcadores, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(uiVerRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMenuAdmin1)
                            .addComponent(uiUsuarioAdmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMenuAdmin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uiCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiAgPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAgPartidosActionPerformed
        // TODO add your handling code here:
        AgregarPartidos_Admin agregar = new AgregarPartidos_Admin(estructurasDatosObject, usuarioActivo);
        agregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uiAgPartidosActionPerformed

    private void uiAgMarcadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAgMarcadoresActionPerformed
        // TODO add your handling code here:
        AgregarMarcador_Admin agregarMarc = new AgregarMarcador_Admin(estructurasDatosObject, usuarioActivo);
        this.setVisible(false);
        agregarMarc.setVisible(true);
    }//GEN-LAST:event_uiAgMarcadoresActionPerformed

    private void uiCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiCerrarSesionActionPerformed
        // TODO add your handling code here:
        Inicio atras = new Inicio();
        atras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uiCerrarSesionActionPerformed

    private void uiVerRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiVerRankingActionPerformed
        TablaPosiciones sigPantalla = new TablaPosiciones(estructurasDatosObject, usuarioActivo);
        sigPantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uiVerRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenúAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenúAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelMenuAdmin;
    private javax.swing.JLabel labelMenuAdmin1;
    private javax.swing.JLabel labelMenuAdmin2;
    private javax.swing.JButton uiAgMarcadores;
    private javax.swing.JButton uiAgPartidos;
    private javax.swing.JButton uiCerrarSesion;
    private javax.swing.JLabel uiUsuarioAdmin;
    private javax.swing.JButton uiVerRanking;
    // End of variables declaration//GEN-END:variables
}
